sudo: false

language: node_js

notifications:
  email:
  - 1025687605@qq.com
  - muyy95@gmail.com
  - 1171009543@qq.com

node_js:
  - 10

before_install:
  - yarn add codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
